image: python:3.7-alpine

services:
  - mysql:5.7

stages:
  - test
  - style


variables:
  MYSQL_HOST: "mysql"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "db_api; CREATE DATABASE test_db_api"
  MYSQL_USER: "db_api"
  MYSQL_PASSWORD: "db_api"

before_script:
  - apk add --update mariadb-connector-c-dev build-base
  - pip install -r requirements.txt
  - cd src
  - python manage.py makemigrations `for i in $(ls -d */); do echo ${i%%/}; done | grep -v 'api' | grep -v 'utils'`
  - python manage.py migrate
  - find -type d -name migrations -prune -exec rm -rf {} \;


test_api:
  stage: test
  only:
    - master
    - develop
  script:
    - python manage.py test


codestyle_api:
  stage: style
  only:
    - master
    - develop
  script:
    - pip install pycodestyle
    - pycodestyle .


docstyle_api:
  stage: style
  only:
    - master
    - develop
  script:
    - pip install pydocstyle
    - pydocstyle .
