image: python:3.7-alpine

services:
  - mysql:5.7

stages:
  - test
  - style


variables:
  MYSQL_HOST: "mysql"
  MYSQL_ROOT_PASSWORD: "root"

before_script:
  - apk add --update mariadb-connector-c-dev build-base
  - pip install -r requirements.txt
  - cd src
  - python manage.py makemigrations --settings=api.test_settings `for i in $(ls -d */); do echo ${i%%/}; done | grep -v 'api' | grep -v 'utils'`
  - python manage.py migrate --settings=api.test_settings
  - find -type d -name migrations -prune -exec rm -rf {} \;


test_api:
  stage: test
  only:
    - master
    - develop
  script:
    - python manage.py test --settings=api.test_settings


codestyle_api:
  stage: style
  only:
    - master
    - develop
  script:
    - pip install pycodestyle
    - pycodestyle .


docstyle_api:
  stage: style
  only:
    - master
    - develop
  script:
    - pip install pydocstyle
    - pydocstyle .
