# Generated by Django 2.0.6 on 2018-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
