# Generated by Django 2.0.6 on 2018-06-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('on', models.BooleanField()),
            ],
        ),
    ]
