# Generated by Django 2.0.6 on 2018-06-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='on',
            new_name='state',
        ),
    ]
