# Generated by Django 2.0.7 on 2018-08-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('minX', models.IntegerField()),
                ('minY', models.IntegerField()),
                ('minZ', models.IntegerField()),
                ('maxX', models.IntegerField()),
                ('maxY', models.IntegerField()),
                ('maxZ', models.IntegerField()),
                ('dimension', models.IntegerField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.Faction')),
            ],
        ),
    ]
