# Generated by Django 2.0.6 on 2018-06-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstack',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemstack',
            name='nbt_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='itemstack',
            name='registry_name',
            field=models.TextField(default=''),
        ),
    ]
