# Generated by Django 2.0.6 on 2018-06-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20180626_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstack',
            name='slot',
            field=models.IntegerField(),
        ),
    ]
